# Generated by Django 5.2.8 on 2026-02-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playvisionapi', '0003_alter_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_national_competition', to='playvisionapi.competition'),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_country', to='playvisionapi.country'),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality_flag',
            field=models.ImageField(upload_to='countryflags/'),
        ),
    ]
